version:  "3"
services: 
  mongo:
    container_name: mongo-container 
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27018:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes: 
      - ./dist:/var/www/clean-node-api/dist
    ports: 
      - "2306:2306"
    links:
      - mongo